### ISSUE TITLE
Clarification on ~2.0@dev

### ISSUE THREAD

**Issue by collizo4sky** [thephpleague/omnipay-braintree#24]
Can someone explain this version tag `~2.0@dev` to me? perused the composer doc but couldn't find doc for `@dev`.

I only saw the use of `dev-master`.

cc @delatbabel @barryvdh

**Comment by barryvdh** [comment]
`@dev` is a stability flag. See https://getcomposer.org/doc/01-basic-usage.md#package-versions
Adding that flag, allows you to get the 'dev' version of the package.
The 2.0 tag does not exist yet, but is aliased to the dev-master. https://github.com/thephpleague/omnipay-braintree/blob/master/composer.json#L42
So in this case will give you the same result as dev-master, but less error prone (because it doesn't install dev-master when on v3 and will validate other package that require this).
